process-engine/management_api_client

package.json, src/accessors/external_accessor.ts, src/accessors/internal_accessor.ts, src/management_api_client_service.ts
Depends on:
* https://github.com/process-engine/management_api_contracts/pull/2
* added a method for getting events for a process model
=> Get events for process model

package.json, src/accessors/external_accessor.ts, src/accessors/internal_accessor.ts, src/management_api_client_service.ts
Depends on:
* https://github.com/process-engine/management_api_contracts/pull/16
* renamed `updateProcessModelById` to `updateProcessDefinitionsByName` to reflect the change of entity
All integration tests in meta repositories should run successfully: 
* https://github.com/process-engine/management_api_meta/pull/6
* https://github.com/process-engine/consumer_api_meta/pull/40
* https://github.com/process-engine/deployment_api_meta/pull/3
* https://github.com/process-engine/process_engine_meta/pull/122
=> Process definitions instead of process model

PULL_REQUEST_TEMPLATE.md, package.json, src/accessors/external_accessor.ts, src/accessors/internal_accessor.ts, src/management_api_client_service.ts
Enhances the Accessors and the Service with functions for the Heatmap feature.
Use the accessors to perform heatmap-related requests.
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:**
PR: #NumberOfThisPR
</code>
</pre>
</details>
<details>
<summary>
Expand for a list of …
=> ✨ Feature/implement heatmap

package.json, src/accessors/external_accessor.ts, src/accessors/internal_accessor.ts, src/management_api_client_service.ts
Requires:
https://github.com/process-engine/management_api_contracts/pull/19
**Changes:**
1. Change all dependencies to fixed versions
2. Implement the `getProcessModelForCorrelation` function
**Issues:**
Closes #13 
PR: #14
Call the function.
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:** …
=> ✨ Get process model for correlation 

package.json, src/accessors/external_accessor.ts, src/accessors/internal_accessor.ts, src/management_api_client_service.ts
**Changes:**
1. Remove `ManagementContext` and `ManagementRequest`.
2. Rename `IManagementApiService` to `IManagementApi`.
2. Replace the `ManagementContext` with the users identity on the `IManagementApi` interface.
PR: #16 
Use the client to run requests against the management api.
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:** …
=> 🔥 Remove execution context

package.json, src/accessors/external_accessor.ts, src/accessors/internal_accessor.ts, src/management_api_client_service.ts
**Changes:**
Add the following functions to the ManagementAPI interface:
- `getAllCorrelations`: Gets all stored correlations
- `getActiveCorrelations`: gets all active correlations
- `getCorrelationById`: Gets a specific correlation by its ID
- `getCorrelationsByProcessModelId`: Gets all Correlations in which a specific ProcessModel was run
- `getCorrelationByProcessInstanceId`: Gets the Correlation in which a specific ProcessInstance was run
PR: #17
Use the client to request correlation related data.
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code> …
=> ✨ Inspect correlation features

package.json, src/accessors/external_accessor.ts, src/accessors/internal_accessor.ts, src/management_api_client_service.ts
**Changes:**
1. Added `socket.io-client` to dependencies.
2. Added method `initializeSocket` to `ManagementApiClient` to allow for socket initialization with a specific identity used for all socket communication.
3. Implemented methods `onUserTaskWaiting`, `onUserTaskFinished`, `onProcessTerminated` and `onProcessEnded` on `InternalAccessor`, `ExternalAccessor` and `ManagementApiClient` to subscribe for new message types.
**Issues:**
https://github.com/process-engine/process_engine_runtime/issues/71
PR: #15 
---
See https://github.com/process-engine/consumer_api_meta/pull/48.
<details>
<summary>
</summary>
<br>
Please use `:twisted_rightwards_arrows:` at …
=> ✨ Add async notifications

package.json, src/accessors/external_accessor.ts, src/accessors/internal_accessor.ts, src/management_api_client_service.ts
**Changes:**
1. Add optional correlationId parameter to `getProcessModelLog` method to only return ProcessModelLogs for a specific correlation.
2. Reorder some methods so each UseCases methods are grouped together instead of spread out across the class.
3. Reverse parameter order in `getTokensForFlowNodeInstance` function.
PR: #18
Use the client to request ProcessModelLogs for a specific Correlation.
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
To get your commit message, …
=> ✨ Filter logs by correlation

package.json
**Changes:**
1. Add the `name` property to UserTasks.
2. Upgrade gulp to 4.0.0 to close vulnerabilities. 
**Issues:**
PR: #19
Request a list of UserTasks and see that they now contain a UserTasks name.
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:**
PR: #NumberOfThisPR …
=> ✨ Add the UserTask name

package.json, src/accessors/external_accessor.ts, src/accessors/internal_accessor.ts, src/management_api_client_service.ts
**Changes:**
1. Use Instance IDs for UserTask Events, instead of ModelIds.
* This ensures that only one UserTask can ever be finished by a single request.
2. Add missing `socket.io-client` dependency.
**Issues:**
Part of https://github.com/process-engine/process_engine_runtime/issues/126
PR: #20
Use the client to make requests for finishing UserTasks.
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre> …
=> ♻️🔒 Use unique ids for UserTask events 

package.json, src/accessors/external_accessor.ts, src/accessors/internal_accessor.ts, src/management_api_client_service.ts
**Changes:**
1. Add delete process model functionality
**Issues:**
Related to https://github.com/process-engine/process_engine_runtime/issues/64
PR: #22
- **Have a look at https://github.com/process-engine/process_engine_runtime/pull/141**
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:**
Closes …
=> ✨ Add Delete Process Model Functionality

package.json, src/accessors/external_accessor.ts, src/accessors/internal_accessor.ts, src/management_api_client_service.ts
**Changes:**
1. Implement client methods for the Event API.
2. Rename `getEventsForProcessModel` to `getStartEventsForProcessModel`
PR: #23
Use the Client to access the Event API functions.
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:**
PR: #NumberOfThisPR
</code> …
=> ✨ Implement event api

package.json, src/accessors/external_accessor.ts, src/accessors/internal_accessor.ts, src/management_api_client_service.ts
**Changes:**
1. Add identity to events
**Issues:**
Related to https://github.com/process-engine/process_engine_runtime/issues/142
PR: #25
- **Have a look at https://github.com/process-engine/process_engine_runtime/pull/151**
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:**
Closes …
=> 🔒 Add Identity to Events

package.json, src/accessors/external_accessor.ts, src/accessors/internal_accessor.ts, src/management_api_client_service.ts
**Changes:**
1. Add ManualTask for External Accessor
2. Add ManualTask for Internal Accessor
3. Add ManualTask on ManagementApiClientService
**Issues:**
Part of https://github.com/process-engine/process_engine_runtime/issues/91
PR: #21
---
See the [examples](#example) for inspiration.
> Describe how others can test your changes (you can remove this section for typo fixes etc.)
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
To get your commit message, just copy the first part …
=> ✨Implement ManualTask

package.json, src/accessors/external_accessor.ts, src/accessors/internal_accessor.ts, src/management_api_client_service.ts
---
**Changes:**
1. Add a method which calls a Callback when the ProcessInstance was started
**Issues:**
Related: https://github.com/process-engine/process_engine_runtime/issues/134
PR: #24
---
See the [examples](#example) for inspiration.
> Describe how others can test your changes (you can remove this section for typo fixes etc.)
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code> …
=> ✨ Add a method which calls a Callback when the ProcessInstance was started

package.json, src/accessors/external_accessor.ts, src/accessors/internal_accessor.ts, src/management_api_client_service.ts
**Changes:**
1. Add function to get ActiveToken by Correlation and ProcessModel
2. Add function to get TokenHistory by Correlation and ProcessModel
PR: #26
- **Have a look at https://github.com/process-engine/bpmn-studio/pull/1152**
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:**
Closes …
=> ✨Add Function For LiveExecutionTracker

package.json, src/accessors/external_accessor.ts, src/accessors/internal_accessor.ts, src/management_api_client_service.ts
**Changes:**
1. Use TokenHistoryGroup as return type for retrieving the TokenHistory for a ProcessModel in a Correlation.
PR: #27
- **Have a look at https://github.com/process-engine/bpmn-studio/pull/1152**
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:**
PR: …
=> 💄 Use TokenHistoryGroup

package.json
**Changes:**
Upgrade all contracts packages to keep the package up to date.
**Issues:**
Part of https://github.com/process-engine/process_engine_runtime/issues/198
PR: #29
All should run as before.
=> ✨ Get instances and tasks by identity

package.json, src/accessors/external_accessor.ts, src/accessors/internal_accessor.ts, src/management_api_client_service.ts
> Related to https://github.com/process-engine/process_engine_runtime/pull/194
**Changes:**
1. Add getTokensForProcessInstance
2. Add getActiveTokensForProcessInstance
PR: #28 
-  **Have a look at https://github.com/process-engine/bpmn-studio/pull/1225**
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ... …
=> ✨ Add Get Token by Process Instance Functionality

package.json, src/accessors/external_accessor.ts, src/accessors/internal_accessor.ts, src/management_api_client_service.ts
**Changes:**
Update all type references to the new structure used by the `ManagementApiContracts` package.
PR: #30
This only changes the type imports, so all should run as before.
=> ♻️ 💄 Refactor Namespaces and API interfaces

package.json, src/accessors/external_accessor.ts, src/accessors/internal_accessor.ts, src/management_api_client_service.ts
> Related to process-engine/process_engine_runtime#207
**Changes:**
1. Add getProcessModelByProcessInstanceId
PR: #31
-  **Have a look at https://github.com/process-engine/bpmn-studio/pull/1225**
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:**
PR: #NumberOfThisPR …
=> ✨ Add getProcessModelByProcessInstanceId

package.json, src/accessors/external_accessor.ts, src/accessors/internal_accessor.ts, src/management_api_client_service.ts
**Changes:**
1. Add `TerminateProcessInstance` functionality.
**Issues:**
Part of https://github.com/process-engine/process_engine_runtime/issues/199
PR: #37
=> ✨Make Processes Interruptible

package.json, src/accessors/external_accessor.ts, src/accessors/internal_accessor.ts, src/management_api_client_service.ts
> Related to https://github.com/process-engine/process_engine_runtime/pull/306
**Changes:**
1. Add Functions to Get Logs by ProcessInstanceId
PR: #39
> **Have a look at https://github.com/process-engine/bpmn-studio/pull/1448***
=> ✨ Add Functions to Get Logs by ProcessInstanceId

package.json, src/accessors/external_accessor.ts, src/accessors/internal_accessor.ts, src/management_api_client_service.ts
**Changes:**
Rename the `getTokensForFlowNodeInstance` UseCase to `getTokensForFlowNode`.
**Issues:**
Part of https://github.com/process-engine/process_engine_runtime/issues/311
PR: #40
All UseCases previously handled by `getTokensForFlowNodeInstance` are now handled by `getTokensForFlowNode`.
=> ♻️💄 Fix naming inconsistencies

package.json, src/accessors/external_accessor.ts, src/accessors/internal_accessor.ts, src/management_api_client_service.ts
**Changes:**
1. Add getTokensForFlowNodeByProcessInstanceId to ExternalAccessor
2. Add getTokensForFlowNodeByProcessInstanceId to InternalAccessor
3. Add getTokensForFlowNodeByProcessInstanceId to Client Service
**Issues:**
Closes #https://github.com/process-engine/bpmn-studio/issues/1464
PR: #38 
---
See the [examples](#example) for inspiration.
> Describe how others can test your changes (you can remove this section for typo fixes etc.)
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code> …
=> ✨Add getTokensForFlowNodeByProcessInstanceId

package.json, src/accessors/external_accessor.ts, src/accessors/internal_accessor.ts, src/management_api_client_service.ts
1. Add Events for Call Activities
2. Add Events for Boundary Events
3. Add Events for Intermediate Events
PR: #41
> Related to https://github.com/process-engine/process_engine_runtime/pull/334
> **Have a look at https://github.com/process-engine/bpmn-studio/pull/1412**
=> ✨ Add Events for Call Activities, Boundary Events and Intermediate Events

package-lock.json, package.json, src/accessors/external_accessor.ts, src/accessors/internal_accessor.ts, src/management_api_client_service.ts
1. Implement `getAllActiveCronjobs` UseCase
Part of https://github.com/process-engine/process_engine_runtime/issues/363
PR: #46
- Deploy some ProcessModels with cyclic `TimerStartEvents`
- Start the CronjobService
- Access `getAllActiveCronjobs` and see that a list with all cronjobs is returned
=> ✨Add getActiveCronjobs UseCase

package-lock.json, package.json, src/accessors/external_accessor.ts, src/accessors/internal_accessor.ts, src/management_api_client_service.ts
Implement UseCases for retrieving a cronjob history.
Part of https://github.com/process-engine/process_engine_runtime/issues/365
PR: #47
=> ✨Persist cronjob history

Jenkinsfile, package.json
1. Use New Release Process
PR: #49
=> ✨ Use New Release Process

package.json
=> ⬆️ Update 'ci_tools'

package.json, src/accessors/external_accessor.ts, src/accessors/internal_accessor.ts, src/management_api_client.ts
1. Make Payload Optional for StartProcessInstance
Related to process-engine/process_engine_runtime#371
PR: #51
=> ♻️ Make Payload Optional for StartProcessInstance

Jenkinsfile, package.json, src/accessors/external_accessor.ts, src/accessors/internal_accessor.ts, src/management_api_client.ts
1. Add `offset` and `limit` to each query that returns a list of values
2. Reorder the UseCases 
Part of https://github.com/process-engine/process_engine_runtime/issues/379
PR: #53
=> ✨ Add limit and offset to list queries

package.json, src/accessors/external_accessor.ts, src/accessors/internal_accessor.ts, src/management_api_client.ts
1. Add events for cronjobs
PR: #52 
> Describe how others can test your changes (not required when fixing typos, linter errors and such)
=> ✨ Add cronjob events

package.json, src/accessors/external_accessor.ts, src/accessors/internal_accessor.ts, src/management_api_client.ts
1. Add total count
PR: #55 
> Describe how others can test your changes (not required when fixing typos, linter errors and such)
=> ✨ Add total count

package.json, src/accessors/external_accessor.ts, src/accessors/internal_accessor.ts, src/management_api_client.ts
1. Add Get Tasks Functionality
Related to https://github.com/process-engine/process_engine_runtime/issues/380
PR: #54
=> ✨ Add Get Tasks Functionality

package.json, src/accessors/external_accessor.ts, src/accessors/internal_accessor.ts, src/management_api_client.ts
1. Remove all the deprecated `CallActivity` notifications
PR: #56
=> 🔥 Remove CallActivity notifications

src/accessors/external_accessor.ts
1. Make external accessor backward compatible
PR: #57 
> Describe how others can test your changes (not required when fixing typos, linter errors and such)
=> 🐛Make external accessor backward compatible
